### ISSUE TITLE
New Book Suggestions

### ISSUE THREAD

**Issue by gozeloglu** [G-khan/the-software-engineer-library#1]
I want to add two books about OS and databases.

* [Operating System Concepts](https://www.amazon.com/Operating-System-Concepts-Abraham-Silberschatz/dp/1119800366/ref=sr_1_1?crid=99ETNAIF4VSJ&keywords=operating+system+concepts&qid=1636720438&sprefix=operating+system%2Caps%2C301&sr=8-1) - Abraham Silberschatz & Greg Gagne & Peter B. Galvin
* [Database System Concepts](https://www.amazon.com/Database-System-Concepts-Abraham-Silberschatz/dp/1260084507/ref=sr_1_1?crid=2GB3GPIXJKKS6&keywords=database+system+concepts&qid=1636720550&s=books&sprefix=database+system+concepts+%2Cstripbooks-intl-ship%2C291&sr=1-1) -  Abraham Silberschatz  & Henry Korth & S. Sudarshan

**Comment by G-khan** [comment]
You can add these books to related category. Thank you for your suggestions.
