### ISSUE TITLE
New book suggestion

### ISSUE THREAD

**Issue by fevziomurtekin** [G-khan/the-software-engineer-library#3]
I want to add book about mobile application
- [Building Mobile Apps at Scale: 39 Engineering Challenges](https://www.amazon.com/gp/product/1638778868/ref=dbs_a_def_rwt_hsch_vapi_tpbk_p1_i0) - Gergely Orosz

**Comment by G-khan** [comment]
Sure, if there is more books suggestion about mobile development then we can create a new category for it. It is okay for now.

**Comment by G-khan** [comment]
Thanks, it is merged.
